### ISSUE TITLE
Fetch from url

### ISSUE THREAD

**Issue by Bjwebb** [notshi/portald#3]
Could this also support fetching data from a url, in addition to being able to POST it?

**Comment by xriss** [comment]
Sure, it just opens up a can of security questions that I didn't want to worry about :)

I'll have a think about how best to deal with all that and then add it in.

**Comment by xriss** [comment]
added xmlurl examples to https://github.com/notshi/portald/blob/main/upload.md

**Comment by Bjwebb** [comment]
Looks good, thanks!
